import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.scss";
import Sidebar from "./components/SibebarContents";
import Mobile_sidebar from "./components/Mobile_sidebar";
import Image from "next/image";
import BG from "../../images/main_bg.png";
import Nav_buble from "./components/Nav_buble";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Mobile_sidebar />
        <Image className={styles.main_bg} src={BG} alt="background_picture" />
        <div className={styles.parent}>
          <div id="main_body" className={`  ${styles.child}`}>
            <div className={`grid grid-cols-12 ${styles.main_body}`}>
              <div className=" hidden lg:block md:col-span-4 xl:col-span-3 ">
                <Sidebar />
              </div>
              {children}
            </div>
            <Nav_buble />
          </div>
        </div>
      </body>
    </html>
  );
}
